### ISSUE TITLE
Webpack v2.1.0-beta.23 breaks build

### ISSUE THREAD

**Issue by elebescond** [SIGSEV/minus#14]
webpack 2.1.0-beta.23 configuration is validated against a schema

cf https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.23

The configuration of minus fails :

    minus\node_modules\webpack\lib\webpack.js:16 throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
    WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

**Comment by meriadec** [comment]
Thanks for reporting ! :)
