### ISSUE TITLE
XSS Attack

### ISSUE THREAD

**Issue by elebescond** [SIGSEV/minus#15]
Attack sample :

    http://localhost:3000/?test=%3C/script%3E%3Cscript%3Ealert(%27failed%27)%3C/script%3E

Serialization of initialState with JSON.stringify will make minus vulnerable to XSS attacks!!! You should use https://www.npmjs.com/package/serialize-javascript instead

    https://github.com/SIGSEV/minus/blob/master/src/components/Html.js#L14

**Comment by meriadec** [comment]
you're right. thanks for reporting!
