### ISSUE TITLE
Don't treat yarn.lock as binary

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/minus#19]
Actually I find it pretty annoying to not be able to diff my yarn.lock, so I usually delete the .gitattributes temporary to be able to diff correctly. I don't think treating yarn.lock as binary is useful.

Opinion?

![2017-07-28-144826_489x115_scrot](https://user-images.githubusercontent.com/315259/28717895-ee620edc-73a3-11e7-82f9-1d425c2fd9fa.png)

**Comment by pierre-github** [comment]
Yep ! :+1: 
Totally agree with that !
On all my projects I like to diff yarn.lock visually (checking all is ok, etc.).
So definitely a YES  !

Pierre .

**Comment by meriadec** [comment]
Thanks @pierre-github :wink:

**Comment by Apercu** [comment]
First of all, I don't remember ever allowing people living unironically in Lons Le Saunier to contribute to this repository, @pierre-github if you ever interact here I will be forced to take drastic measures into banning your account and engaging legal pursuits given you are currently raping me.

With that out of the way, I'm not sure diffing a lockfile would be a good idea. Indeed, if a single or more dependencies have been updated, the new one should be the single source of truth. Trying to merge the old one with sub-dependencies or other shit that might no longer exists seems like a waste of time to me.

**Comment by meriadec** [comment]
> I'm not sure diffing a lockfile would be a good idea

Believe me, it is useful in some cases :stuck_out_tongue_winking_eye: .

> [...] if a single or more dependencies have been updated, the new one should be the single source of truth

Not everytime :wink: ! When adding deps on branch A, and *different deps* on branch B is a totally common case, for example. And you don't want to discard the older `yarn.lock`.

Also, this file is, *by essence* not a binary file (I mean it can be identified as ***non-binary***), so treating it like that also sounds like a semantic problem to me. It structure is pretty simple and is meant to be human readable. You can learn more about `yarn.lock` structure [here](https://yarnpkg.com/blog/2017/05/31/determinism/).

@pierre-github Lons-le-Saunier is a pretty nice place! :+1:

**Comment by pierre-github** [comment]
:+1: good points @meriadec ^^

For additional reading, this has been discussed on the yarn repository: [Should yarn.lock be treated as a binary file in git?](https://github.com/yarnpkg/yarn/issues/1776) and seems to not be recommended, although.

Pierre .
