### ISSUE TITLE
Drop eslint-config-zavatta{,-react}

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/minus#26]
in favor of more standard ones (airbnb much?)

**Comment by balthazar** [comment]
Do you know what are the most annoying rules it would imply?

**Comment by meriadec** [comment]
Don't have the complete list in mind, here are a few I have for a project I work for

```
    "no-await-in-loop": 0,
    "no-restricted-globals": 0,
    "no-unused-expressions": 0,
    "no-nested-ternary": 0,
    "no-param-reassign": 0,
    "no-plusplus": 0,
    "no-return-assign": 0,
    "no-shadow": 0,
    "no-underscore-dangle": 0,
    "no-console": 2,
    "no-use-before-define": 0,
    "no-restricted-syntax": 0,
    "no-prototype-builtins": 0,
    "no-void": 0,
```

but ye. Basically we'll have to disable useless rules one by one.

**Comment by balthazar** [comment]
So effectively we would use one "standard" but overriding it, which defies a bit the _purpose_ of using another standard no? Shouldn't we keep zavatta, and extend it with airbnb and these rules you have?

**Comment by meriadec** [comment]
here are the advantages I see of directly using airbnb (or other standard, maybe [eslint-config-standard](https://github.com/standard/eslint-config-standard))

- don't need to maintain separate zavatta :hankey: package, then publish, then bump in minus (which is like the only project in the world using this config), then realize you forgot a rule, then correct, then publish, then bump, then realize you forgot other rule, then kill yourself
- benefit of updates from standard package which is updated by people. open source ftw
- why not eh

**Comment by balthazar** [comment]
Good enough
