### ISSUE TITLE
include axios?

### ISSUE THREAD

**Issue by meriadec** [SIGSEV/minus#8]
It appear that we currently don't have `superagent` as a dependency, but we are used to add it to project based on minus. Should we reconsiderate this choice, and choose [axios](https://github.com/mzabriskie/axios) instead? I think so. It's API sounds more friendly, is promise-based, and is isomorphic too.

Opinion?

**Comment by meriadec** [comment]
As an additionnal argument, I would say it also have a [bower](https://github.com/bower/bower) support.

![](https://pbs.twimg.com/profile_images/3536632979/66db62603f426a8fc6664081811be6d4_normal.png)

**Comment by Apercu** [comment]
Cool, so we can add [this](https://github.com/lpiepiora/bower-webpack-plugin) now right?

**Comment by meriadec** [comment]
I think it should be included in the webpack source code. By default.
bower isn't the best package manager?

**Comment by Apercu** [comment]
I'm making an issue about this while we speak.

**Comment by meriadec** [comment]
Bye.
